apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  annotations:
    com.ibm.mq/write-defaults-spec: 'false'
  name: qmd1
  namespace: mq
  finalizers:
    - finalizer.queuemanagers.mq.ibm.com
spec:
  license:
    accept: true
    license: L-JTPV-KYG8TF
    use: NonProduction
  queueManager:
    name: QMD1
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    storage:
      queueManager:
        type: ephemeral
  version: 9.4.0.6-r1
  web:
    console:
      authentication:
        provider: manual
      authorization:
        provider: manual
    enabled: false
