apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: sed-hrq8 
spec:
  enableMetrics: true
  license:
    accept: true
    license: L-XRNH-47FJAW
    use: CloudPakForIntegrationProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 1300m
            memory: 1368Mi
          requests:
            cpu: 120m
            memory: 368Mi
  adminServerSecure: false
  router:
    timeout: 120s
  env:
    - name: MQSI_PREVENT_CONTAINER_SHUTDOWN
      value: 'true'
  designerFlowsOperationMode: disabled
  createDashboardUsers: true
  service:
    endpointType: http
  version: '12.0'
  replicas: 1
