apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjcC5pY3IuaW8iOnsidXNlcm5hbWUiOiJjcCIsInBhc3N3b3JkIjoiZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcGMzTWlPaUpKUWswZ1RXRnlhMlYwY0d4aFkyVWlMQ0pwWVhRaU9qRTJNRE16TVRnek1UWXNJbXAwYVNJNklqQTFNR0ptWVRWbFl6ZzJOelF6TW1JNFkyTmxZV05tTm1ReFl6UXlZVEF5SW4wLng3aXFOV2ljNlpVX3g0WjRTYzE3VGNrYkMyR2R4WEFSdzVDUTFjbWNnWDQiLCJhdXRoIjoiWTNBNlpYbEthR0pIWTJsUGFVcEpWWHBKTVU1cFNqa3VaWGxLY0dNelRXbFBhVXBLVVdzd1oxUlhSbmxoTWxZd1kwZDRhRmt5VldsTVEwcHdXVmhSYVU5cVJUSk5SRTE2VFZSbmVrMVVXWE5KYlhBd1lWTkpOa2xxUVRGTlIwcHRXVlJXYkZsNlp6Sk9lbEY2VFcxSk5Ga3lUbXhaVjA1dFRtMVJlRmw2VVhsWlZFRjVTVzR3TG5nM2FYRk9WMmxqTmxwVlgzZzBXalJUWXpFM1ZHTnJZa015UjJSNFdFRlNkelZEVVRGamJXTm5XRFE9In19fQ==
kind: Secret
metadata:
  name: ibm-entitlement-key
  namespace: mq
type: kubernetes.io/dockerconfigjson
