apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility
  namespace: utility
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: utility
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: utility
    spec:
      containers:
      - image: quay.io/danutek_us/utility:1
        imagePullPolicy: IfNotPresent
        name: utility
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: utility
      serviceAccountName: utility
      terminationGracePeriodSeconds: 30

