apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: generic-crossdist-asn2c-eg01
spec:
  type: generic
  contents: |-
    UEsDBBQAAAAIAN1zm1TdK/JaLAEAANsCAAAPABwAZGIyZHNkcml2ZXIuY2ZnVVQJAAOhU2lioVNp
    YnV4CwABBOsDAAAE6wMAAMWSy27CMBBF1+UrLO/zII8GpAQkmnZFH2pgjQbbBFeOHdlO2v59k9Cg
    gtQ1y7HnzhwfOV1+VQK1TBuuZIanro8Rk0RRLssMbzdPzgwjY0FSEEqyDEuF0XIxSYmSB142GmwX
    XEwQSilY2INhpq/+1OiojM1wGLMoJn7gxGGcONE8AmcehIGTzOaRT8OY7unU3ds2mn2QT7+m9P4Q
    yapsS7fWvAXL3PMCF+qaqgq4dIlQDcVIQtWxrdbbfIVRrXS/b5r4CT6xdDQ16K7HMv3bWzDSaG6/
    Nxqk6RPPijKMWhBNf1ussfdv9qHRmklbkCOr4Jx5LFZv76/5mEu9kXew413oSanpJAvByKjvdIZA
    cDDDrN0w7KbyupfcXVEF/i4vXm6ONQi9VJh6V1/yB1BLAwQUAAAACACqdM1UFxcj03ECAACRAwAA
    DgAcAHByb3BlcnRpZXMuamFyVVQJAAOgS6dioEunYnV4CwABBOsDAAAE6wMAAAvwZmYRYeDg4GBY
    VXI2hAEJcDKwMPi6hjjqevq56f87xcDAzBDgzc4BkmKCKgnAqVkEiOGafR39PN1cg0P0fN0++545
    7eOtq3eR11tX69yZ85uDDK4YP3hapOflq+Ppe7F0FQtnxAvJI9IzJbQyKqx+alk8Fxd9Iq46jUE0
    +1PRxyJGsBM8/XUPOQItcEJxwp3i2ShO4AfirJSkZL2CovyC1KKSzNTi0P7o4iYDgdb7P3WFJrA4
    Wp0pYdga5qj365K4uopmK+MhAb3L9fFLrvXl/35rWV02fdvPA1HbjzjdaAlX8Nd2COYVaWE4f3FP
    5DSO9dluu+Zcn/4jQ9xE9VrKJhHWVzwvXa6myL5q67nGcTqbN2tT4rqJXgv9gnexZJorbFZYfCtg
    1y+X0qm8khnLUu4YOhS2B+vMYNiRqbG+II456NO8qILMFW2PZPTnJXMG7uqXfrPu7c3uK9zX3tlW
    T7ZIrPmUxrPc3O1eUHV9Q3LBja83v7d//KY3J9xzgn7YQ4bwN4YXt+yZIZRf01t5/2mpmP6dE9+F
    i1Nf3S7ima8R92O38fwfuwonx3+b/Plkr9q8s/4Wqw9e6/23pLr2/of5da//gsNTm8GDUZiRgaGN
    ETk8l6btRglPASDOyU83yUIK0M8fy80/dvFzfOIv4OXq7Cn//KVw69XzJ877XvX38dPV9dO95O9/
    1lv3lM+18yf9zU9eWn3iLCQK90l6rjUFGmgMjkJGJhEG1HQES2GgRIgKUJIkulbklCGCos0WR4JE
    NgGUgpDDgh/FhAOY6QlZMyi4kH0lgKJZgAkz8AK8WdlAcixA+ANIN4M9DQBQSwMEFAAAAAgApWa7
    VCdx5/nRBQAAMRMAAAkAHABsb2c0ai5kdGRVVAkAA7bJkGK2yZBidXgLAAEE6wMAAATrAwAAvVdb
    cxo3FH6GX3FKHgqeNa4zfeh4kjCuwS0zdsZNcKd9FLsCFGslutLaocOP75G0ugCLk3gy1Ywx6EhH
    n75z1ZvR55LDI60Uk+Jt73z4Uw+oyGXBxPJt7352ffpLD0bvut03P5yewmWtV7JSF3C1qpiCGdlw
    WWVwRR8Y/FbzvB7C6alf/KdTegHnw9fJ9CXkUizYsq6IRjFQTksqtJlVTGkFcgFybUSEQ0VFQSta
    dZtVKiPrtZ2DMAM50XQpK0YVEFHgX7JfSu33BmyTm8nt5P0MuFz+/OliF03fn3iSgT/qJOs3R2y2
    uGdJq8FJZjSPsi48P/y+a5Jr/DcaeBZmKwo9vaqoWkle9IBoXbF5rSlo8mAuApw+UrQM4TUFVecr
    0CuigXBur2GVGDBoJ1Aaj7FkwBPTq7CZ/lMjB7KCOeXyCRWgzZxCUtGopmCKzDktUuN9pFob1drg
    LOi8Xhq/MMvs1LpiwsrRWPiNVoZsy2cABfGAiG/4Bb6Ojwjt1w0UdEFqrjOwyBLy8II9UXPey6Ck
    RLgbIG1PFITUUEjQ0nAZoB0Br9z1Ea81lFXZULdAPg0FwXhRWcSRoxPOKZRMcUpMLDlFcc+CUfxE
    9gj6+FoqZtyjE1WhAgMYdSAUBA0GwlehiSAi/6xc841lRCEH4kfd0KAPMWVtk45/cNoeKF0rYCZS
    UWJhfLNZDTT7BVVezmY304+t4YhrMD0JdeGsszOuxpezS3h1Pf1rMobeSuv1xdnZJ/JAKk2GZE3y
    FR3Kanlmt571AHXFW+2NPobV1vrSlomF3D6RSmxpVclquyCa8K1cLLaG9kHDPipzrtcy+rqqKe7j
    ijZ7/CbvwT7HhBxmwtoGKIVa4TzaO6+VliX718UbstLkaOMz0bIlVYosKcj5J5qjHtz4Ec1v/O3r
    DZGkxIBscns3+/tdYp2QicF/La44USoY4sPkj/vph8k4LEAUbsX+glAJmvyqoMTLwoo8YmICQUrq
    8jjkZvsw3jbZQDaGE02YMPnemgoViIJTrEeY/8hG1pgfQiFYkwr1arM3hqsw7s3NpI2sjVWLdpN4
    gwXeUOQU+qiYiZzXBR2ARFtUoS4EaJ69UJv6FtDvDs8oc6djRXGwcMIdm9SYUzzxZJAS7iXIp6Wk
    05mOoZPSbOmBjqW3s0dvqHH2ROg7BDsHOJHX03lejwPcqseJvqAH6Z4knCifIU0GFBtvaWsEIyFF
    ybSViLqc48G4Ltgt2vKgpKe8e7CZ7QIMwUi8q9+W7Qx22MfanGajVJNJVY7sndwD0adhly1/oA+j
    3aajAXAYY1Fmg2gB0/GHyfV+5HhN9naHSux04zSNMVKkKLEpu9VOsTfBAo8dlW4sY+oq5lKfVm1K
    Hd7YHmMeqvFeMAQNbT7jhd1IbANnent3M01gHuaXtIVyfc6LMbrtrcFhJC9E5+BNF9hy+Eas6XER
    olrTnGFRdYVW+Oze1DxMNrf3eLyp/cHfY6122jAWzA9j4CJ0mPu5yM+HKOh7zrdWy2CUHc89fnN3
    z++j40ciEj/byU6kKJhmj3hgJ6mIWEDNjx5AsOP/RJQLrn2a3Cz07YbnKHELw32n42++bItxmmdB
    qwfurzmShAKKndyQ3uMwRaTS5zJNME6I5e9ln6AQTWSSZVLkTVibqejBhD+RjQL62T4PTdVOuuN6
    bknxr5fdHBxLwKH3H5Te5sZvv8OIt2kfl+GhgWCQzq9o0r43tt1HsIWBbz4MhPj7IACShc905i9o
    zH1vuzf658Pz7fnwNcYRftqVTSumbmRuXwhTbNdhp+f2QWdDrv2i/pZN95w1svfjq5H/jk8F+WSe
    uzhz7JHvVvIEyWgAaXXSDE/QpFybZ1pJbNig13HmdmBRsh4ogvu3cN1tTjJZqiXqndhmu6Ni8+wh
    xXFxQNleancJ9C+O/qs7u3pw6EzIYyo+kAdun12V8traKu2tibXqsBZht7iSRYsAe1cKbTs4E22C
    d93/AFBLAwQUAAAACABjdM1UKnZnhYUBAADjAwAACQAcAGxvZzRqLnhtbFVUCQADGkunYhpLp2J1
    eAsAAQTrAwAABOsDAAC9U8FugkAQPetXjJtwhG2TNlEDmkZtemhTU+3BND2ssCAKu2R3MfXit3dZ
    QCzR9tZNOM17896bGdzxV5rAngoZc+ahW+cGAWU+D2IWeeh9+Wj30XjUdXvT18lyNZ9BwqO77dDn
    LIyjXBClabBYLZazF0Cm5gQqQJpxCai1mByaioc2SmVDjLdkR4QiDsmIv6EOFxE2AIwgoOtcuwhJ
    Iqlu2YXquT3bBt1Z8oQCyTLKAiocYFxBLmkA64OmhiRPFNj2qKHVUGAkpR6qOiDwEyKlh7R07aJM
    MikBDxUNNa1Mu4QceK6usudEKSrYs0Fpbkc/NyOCpJW+bl8NvoIi2JMk15UPK/gE6z4Dyz8erdTS
    FdwSx6X6WTpcxyukroaW3N9RdT0zo8pZGMxZ7LbzORfqZHYwGPSNvzbqjaZc0ScuG2wenpD/Pb2C
    /9vQOj+mVlyY4PqgtJuoOK7ppYMqEK29ZCLmIlaH2oy5YdTeXq1qCxqC/ppj/BtZbRCfpyiNuPjC
    Tzf6BlBLAQIeAxQAAAAIAN1zm1TdK/JaLAEAANsCAAAPABgAAAAAAAEAAACAgQAAAABkYjJkc2Ry
    aXZlci5jZmdVVAUAA6FTaWJ1eAsAAQTrAwAABOsDAABQSwECHgMUAAAACACqdM1UFxcj03ECAACR
    AwAADgAYAAAAAAAAAAAAgIF1AQAAcHJvcGVydGllcy5qYXJVVAUAA6BLp2J1eAsAAQTrAwAABOsD
    AABQSwECHgMUAAAACAClZrtUJ3Hn+dEFAAAxEwAACQAYAAAAAAABAAAAgIEuBAAAbG9nNGouZHRk
    VVQFAAO2yZBidXgLAAEE6wMAAATrAwAAUEsBAh4DFAAAAAgAY3TNVCp2Z4WFAQAA4wMAAAkAGAAA
    AAAAAQAAAICBQgoAAGxvZzRqLnhtbFVUBQADGkunYnV4CwABBOsDAAAE6wMAAFBLBQYAAAAABAAE
    AEcBAAAKDAAAAAA=
