apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: generic-hlt-20-03
spec:
  type: generic
  contents: |-
    UEsDBBQAAAAIAGtyjVJ48cVKHwEAAEQCAAAPABwAZGIyZHNkcml2ZXIuY2ZnVVQJAAO57nVguliE
    YXV4CwABBO0DAAAEZAAAAMWRy07DMBBF9/0Ky/s82iQkkZxWCoVVEYi0azS13dTIsSPbCfD3JOlD
    FIk1y7HnzhydIavPRqKeGyu0KvDcDzHiimomVF3g3fbRyzCyDhQDqRUvsNIYrZYzQrU6iLoz4Ibg
    coYQYeBgD5bbsfpRo6O2rsBRwuOEhgsviZLUi/MYvHwRLbw0y+OQRQnbs7m/d32cvdOPsGXs7hCr
    pu5rvzWiB8f96wIf2pbpBoTyqdQdw0hBM7CVm926xKjVZtw3T8MUn1gGmhbM0OO4OfdWnHZGuK+t
    AWXHxJNmHKMeZDf+Vhsc/Jm974zhylX0yBu4Zh6q8uX1eX3JkeDCO9kJbvQQZgfJUnJ60Xd6QyAF
    2GnW2zTsX+UFZ/JbVhL8uv03UEsDBBQAAAAIANuWZFNIqqZSfAIAAJsDAAAOABwAcHJvcGVydGll
    cy5qYXJVVAkAA85yhGHOcoRhdXgLAAEE7QMAAARkAAAAC/BmZhFh4ODgYLg9LSWYAQlwMrAw+LqG
    OOp6+rnp/zvFwMDMEODNzgGSYoIqCcCpWQSI4Zp9Hf083VyDQ/R83T77njnt462rd5HXW1fr3Jnz
    m4MMrhg/eFqk5+Wr4+l7sXQVC2fEC8kj0pFSmhksS5dpVKhMe6FR8Uz1deanoo9FjGAXHFoRweQA
    NN8BxQVV6V1ByC7gB+KslKRkvYKi/ILUopLM1OLQ87H+zQYiDQ+r606/kJDflOjBckrmXXeJnlS+
    R6a2k4aqiNuf75N8D8buq6zyq8qYHB8hPCXCazoH36cpzLNeLVBgcYhvDw/rWKHldismJH1LMfcs
    ofSKJ2eetx316c7YlSU5be0sbeHV2ncvhFbvNDLNijBZyj1hm3hx5IS41Zq1P0y058UaBfDPLjzN
    cFTXb2OK0INdy5oe72FaIiJb2tO69mZxfXnbPuVUyZ76gtvLkvu91COFHc1tfhpaHco+dlhyb8YK
    6dzefxtq3216z1/9Wemvuusk/WMfGYvN/K70arT1vnvW8nrCs5Ovf9fFfvv4Zt/FGx8Nd3yO/m/V
    I/TE989089rHRh8XFTxZqf5/f+2r2cr8avfqbH9dyTCLmaxwcWvlVEXXn4ygoA28xZMtx8jAcIER
    OWjDU1EjVwCIc/LTTbKQwvbzx3Lzj138HJ/4C3i5OnvKP38p3Hr1/Inzvlf9ffx0df10L/n7n/XW
    PeVz7fxJf/OTl1afOAuJzX2SnmtNgQYag2OTkUmEATVFwdIaKDmiApTEia4VOZGIoGizxZE0kU0A
    JSbksOBHMWE/ZtJC1gwKLmRfCaBolmLCDLwAb1Y2kBwLEP4A0r1gTwMAUEsDBBQAAAAIAClhh1Ke
    b2XLIQEAABkEAAAMABwAb2RiY2luc3QuaW5pVVQJAAM+521guliEYXV4CwABBO0DAAAEZAAAAK1T
    sWrDMBDd8xUHGTLVpl2Nl6YUOpQu2UqHi3R2RC1dkM4F9+t7kkOhIZS0+C13Eo/H0ztds14Mq6ZZ
    w8vD/RYsCu4xEdjoPiiCx4C91jQlIQ8uOHE4uITiOEDnBqrgJ4rYss6eBFyCSIa9p2DJghxQYOIR
    BN8JEAwfJ+BO75WYXQGGzKIAZJ3k7uSsUM89/wOz2EKYxW4r2LI/DiRUDG+e9REoHCfNvePo59CT
    YPjEDSQy5XxZDOdHa1xzLnRxWFc6WwhLf40/yX2T4bdY4Yx8rZHXvD1vJawdg4wxgGqWlZKIhnRa
    ArvctROlVTO3gU/do86mrQ/sqdbTmCjmeqNVl7A2HDrX1/n7c6gH7mu2e1N0Kx5FNQ6R0LrQt3dq
    5gtQSwMEFAAAAAgAZXK7Uip2Z4WFAQAA4wMAAAkAHABsb2c0ai54bWxVVAkAA67wr2C6WIRhdXgL
    AAEE7QMAAARkAAAAvVPBboJAED3rV4ybcIRtkzZRA5pGbXpoU1PtwTQ9rLAgCrtkdzH14rd3WUAs
    0fbWTTjNe/Pemxnc8VeawJ4KGXPmoVvnBgFlPg9iFnnofflo99F41HV709fJcjWfQcKju+3Q5yyM
    o1wQpWmwWC2WsxdApuYEKkCacQmotZgcmoqHNkplQ4y3ZEeEIg7JiL+hDhcRNgCMIKDrXLsISSKp
    btmF6rk92wbdWfKEAskyygIqHGBcQS5pAOuDpoYkTxTY9qih1VBgJKUeqjog8BMipYe0dO2iTDIp
    AQ8VDTWtTLuEHHiurrLnRCkq2LNBaW5HPzcjgqSVvm5fDb6CItiTJNeVDyv4BOs+A8s/Hq3U0hXc
    Esel+lk6XMcrpK6GltzfUXU9M6PKWRjMWey28zkX6mR2MBj0jb826o2mXNEnLhtsHp6Q/z29gv/b
    0Do/plZcmOD6oLSbqDiu6aWDKhCtvWQi5iJWh9qMuWHU3l6tagsagv6aY/wbWW0Qn6cojbj4wk83
    +gZQSwECHgMUAAAACABrco1SePHFSh8BAABEAgAADwAYAAAAAAABAAAAgIEAAAAAZGIyZHNkcml2
    ZXIuY2ZnVVQFAAO57nVgdXgLAAEE7QMAAARkAAAAUEsBAh4DFAAAAAgA25ZkU0iqplJ8AgAAmwMA
    AA4AGAAAAAAAAAAAAICBaAEAAHByb3BlcnRpZXMuamFyVVQFAAPOcoRhdXgLAAEE7QMAAARkAAAA
    UEsBAh4DFAAAAAgAKWGHUp5vZcshAQAAGQQAAAwAGAAAAAAAAQAAAICBLAQAAG9kYmNpbnN0Lmlu
    aVVUBQADPudtYHV4CwABBO0DAAAEZAAAAFBLAQIeAxQAAAAIAGVyu1IqdmeFhQEAAOMDAAAJABgA
    AAAAAAEAAACAgZMFAABsb2c0ai54bWxVVAUAA67wr2B1eAsAAQTtAwAABGQAAABQSwUGAAAAAAQA
    BABKAQAAWwcAAAAA
